import { Link } from "react-router-dom"

const Terms = () => {
  return (
    <section className="md:p-16 p-8">
      <h2 className="font-Oswald md:text-6xl text-4xl font-bold my-4 uppercase">
        BULL’S Terms of Service
      </h2>
      <Link to="/" className=" absolute right-0 top-0 p-12">
        <img src="/assets/images/backArrow.png" alt="" />
      </Link>
      <p className="md:text-lg text-sm pr-4 md:leading-none">
        Bull's Lodge NFT is a collection of digital artworks (known as NFT's)
        running on the Polygon (Matic) blockchain network. This website is only
        an interface allowing users to purchase (mint) or review digital
        collectibles. Users are entirely responsible for the safety and
        management of their own private Polygon/Matic wallets and validating all
        transactions and contracts generated by this website before approval.
        Since Bull's Lodge NFT smart contract runs on the Polygon network, there
        is no ability to undo, reverse, or restore any transactions that has
        taken place. This website and its connected services are provided
        “as-is” and “as-available” without warranty of any kind. By using this
        website you are accepting our Terms of Service and you are accepting
        entire responsibility for any and all transactions involving Bull's
        Lodge NFT digital collectibles.
      </p>
      <h2 className="font-Oswald md:text-4xl text-3xl font-bold my-4">
        General Provisions
      </h2>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        1. These Terms of Service constitute a legally binding agreement made
        between you, whether personally or on behalf of an entity (“you”), and
        the Bulls Lodge NFT, e-mail: contact@bullslodgenft.com concerning your
        access to and use of our websites as well as any other media form, media
        channel, mobile website or mobile application related, linked, or
        otherwise connected thereto (collectively, the “Site”).
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        2. You agree that by accessing the Site and using resources provided
        therein, you have read, understood, and agree to be bound by all of
        these Terms of Service. If you do not agree with all of these Terms of
        Service or have no legal capacity to be bound to them, then you are
        expressly prohibited from using the Site and resources provided therein,
        and you must discontinue the use immediately.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        3. These Terms of Service, your use of the Site, as well as contracts
        concluded with us are governed by and construed in accordance with laws.
        Those persons who choose to access the Site from other locations do so
        on their own initiative and are solely responsible for compliance with
        local laws, if and to the extent local laws are applicable.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        4. All orders placed through the Site are subject to conditions
        specified in the order page and below.
      </h3>
      <h2 className="font-Oswald md:text-4xl text-3xl font-bold my-4">
        Our Services
      </h2>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        5. We dedicate our Site to Bulls Lodge NFT on the Polygon (Matic)
        Blockchain, you can order through our Site (“Services”).
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        6. To use our Services, you shall place an order through the Site.
        Ordering our Services, you can only pay using cryptocurrency. Payment
        processing companies are separate entities and after selecting their
        payment method, you may be subject to their Terms of Service they
        provide.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        7. Please make your purchases wisely as you are solely responsible for
        every action or transaction you make on the Site. If you are a U.S.
        citizen, please note that we do not operate in U.S. jurisdictions and
        therefore, these Terms of Service will remain the only act giving rise
        to any obligations on our part.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        8. Once your order is performed, you are the sole owner of NFT, mediated
        entirely by the smart contract and Blockchain network technology.
      </h3>
      <h2 className="font-Oswald md:text-4xl text-3xl font-bold my-4">
        Order Performance
      </h2>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        9. All orders are processed within 14 days after receiving your order
        confirmation e-mail, which means in principle your NFT will be minted
        within term of 14 days from your purchase, unless you want us to provide
        contractual services and mint your NFT immediately after purchase (this
        will affect your right to withdrawal and refund – please refer to
        paragraph 14 below). You will receive another notification when your
        order has been performed.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        10. We will contact you via e-mail to the address you provided at
        checkout to notify you on the order performance.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        11. If you experience any problem with your order, please contact us to
        our e-mail address with your name and order number, and we will look
        into it for you.
      </h3>
      <h2 className="font-Oswald md:text-4xl text-3xl font-bold my-4">
        Claims and Complaints
      </h2>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        12. All complaints should be sent to us in documented form, preferably
        to the address indicated in section 1 above, by e-mail or traditional
        mail. The complaint should include: Your first and last name
      </h3>
      <ul className=" md:text-lg md:leading-none mb-2 list-disc list-inside">
        <li>Your mailing address and e-mail address.</li>
        <li>
          Description of the complaint (e.g. to what extent the order has not
          been fulfilled correctly).
        </li>
        <li>Expected state after settling the complaint.</li>
      </ul>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        13. Complaints will be considered within 30 days of their receipt. The
        answer will be sent to the e-mail address provided by you.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        14. We may request you to provide information necessary to solve the
        request, specifying a period not shorter than 7 days and the scope of
        required information, with the instruction that failure to complete the
        request within the specified period will result in the request not being
        considered. After the expiry of the designated deadline, the complaint
        shall not be considered.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        15. Consumers enjoy possibilities of using out-of-court complaint and
        redress procedures. If you wish to follow such procedure, please contact
        us so we might suggest a procedure appropriate for your case. Consumers
        have the following exemplary out-of-court complaint and redress
        procedures:
      </h3>
      <ul className=" md:text-lg md:leading-none mb-2 list-disc list-inside">
        <li>
          Application for out-of-court dispute resolution to a consumer
          arbitration court.
        </li>
        <li>
          FOR EU-BASED CONSUMERS: application for out-of-court dispute
          resolution at online ODR platform for resolving consumer disputes at
          the EU level, available at address http://ec.europa.eu/consumers/odr.
          The ODR platform is a multilingual website providing complex services
          for consumers and entrepreneurs seeking out-of-court settlement of a
          dispute regarding contractual obligations arising from an online sales
          contract or a contract for the provision of services.
        </li>
      </ul>
      <h2 className="font-Oswald md:text-4xl text-3xl font-bold my-4">
        Withdraw and Refund Policy
      </h2>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        16. If you are a consumer, in principle you can resign from the purchase
        within 14 days and during this time we will withhold our services, i.e.
        minting the NFT. Nonetheless, you can decide to receive the NFT earlier
        and we will mint it at your request, but please note that making such
        request you will lose your right to withdraw from your purchase.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        17. Detailed information for persons entitled to the right to
        withdrawal:
      </h3>
      <ul className=" md:text-lg md:leading-none mb-2 list-disc list-inside">
        <li>
          You have the right to withdraw from the contract within 14 days
          without giving any reason.
        </li>
        <li>
          The deadline to withdraw from the contract will expire after 14 days
          from the order submitting or performance of the contract by delivery
          of the order.
        </li>
        <li>
          To exercise your right of withdrawal, you must notify us to the
          contact details specified in section 1 of the Terms of Service, of
          your decision to withdraw from this contract by an unequivocal
          statement (e.g. a letter sent via the website or via e-mail).
        </li>
        <li>
          You can use the withdrawal template below, but it is not obligatory.
        </li>
        <li>
          In order to keep the deadline for withdrawing from the contract, it is
          enough for you to send information regarding the exercise of your
          right to withdraw from the contract before the deadline for
          withdrawal.
        </li>
      </ul>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        18. The model withdrawal template that can be copied and completed only
        if you wish to withdraw from the contract is as follows:
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        17. Detailed information for persons entitled to the right to
        withdrawal:
      </h3>
      <ul className=" md:text-lg md:leading-none mb-2 list-disc list-inside">
        <li>Addressee: (our details from section 1 of the Terms of Service)</li>
        <li>
          I (*) inform (*) about my withdrawal from the contract for the
          provision of the following services (*)
        </li>
        <li>The date of conclusion of the contract (*)</li>
        <li>Name and surname of the consumer(s)</li>
        <li>Address of the consumer(s)</li>
        <li>
          Signature of the consumer(s) (only if the form is sent in paper
          version)
        </li>
        <li>Date</li>
      </ul>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        19. Consequences of withdrawal from the contract: In the event of
        withdrawal from this contract, we will refund all payments received from
        you, immediately and in any case, no later than 14 days from the date on
        which we were informed about the decision to exercise the right to
        withdraw from this contract. Refunds will be made using the same payment
        methods that were used in the original transaction, unless expressly
        agreed otherwise; in no event will you incur any fees related to this
        return.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        20. If you withdraw from the contract and request a refund, you are
        required to send us the ordered products at your own expense, to our
        address specified in section 1 of the Terms of Service.
      </h3>
      <h2 className="font-Oswald md:text-4xl text-3xl font-bold my-4">
        User Representations
      </h2>

      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        21. By using the Site, you represent and warrant that:
      </h3>
      <ul className=" md:text-lg md:leading-none mb-2 list-disc list-inside">
        <li>
          All information you submit will be true, accurate, current, and
          complete.
        </li>
        <li>
          You will maintain the accuracy of such information and promptly update
          such registration information, as necessary.
        </li>
        <li>
          You have the legal capacity, and you agree to comply with these Terms
          of Service.
        </li>
        <li>You are not a minor in the jurisdiction in which you reside. </li>
        <li>
          You will not access the Site through automated or non-human means,
          whether through a bot, script, or otherwise.
        </li>
        <li>
          You will not use the Site for any illegal or unauthorized purpose.
        </li>
        <li>
          Your use of the Site will not violate any applicable law or
          regulation.
        </li>
      </ul>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        22. If you provide any information that is untrue, inaccurate, not
        current, or incomplete, we have the right to suspend or terminate your
        account and refuse any and all current or future use of the Site (or any
        portion thereof).
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        23. Whenever you register with the Site, you agree to keep your password
        confidential and will be responsible for all use of your account and
        password. We reserve the right to remove, reclaim, or change a username
        you select if we determine, in our sole discretion, that such username
        is inappropriate, obscene, or otherwise objectionable.
      </h3>
      <h2 className="font-Oswald md:text-4xl text-3xl font-bold my-4">
        Intellectual Property Rights
      </h2>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        24. Unless otherwise indicated, the Site, all source code, databases,
        functionality, software, website designs, audio, video, text,
        photographs, and graphics on the Site (collectively, the “Content”) and
        the trademarks, service marks, and logos contained therein (the “Marks”)
        are owned or controlled by us or licensed to us, and are protected by
        copyright and trademark laws and various other intellectual property
        rights and unfair competition laws, foreign jurisdictions, and
        international conventions.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        25. The Content and the Marks are provided on the Site “AS IS” for your
        information and personal use only. Except as expressly provided in these
        Terms of Service or in any other binding agreement with us, no part of
        the Site and no Content or Marks may be copied, reproduced, aggregated,
        republished, uploaded, posted, publicly displayed, encoded, translated,
        transmitted, distributed, sold, licensed, or otherwise exploited for any
        commercial purpose whatsoever, without our express prior written
        permission.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        26. Provided that you are eligible to use the Site, you are granted a
        limited license to access and use the Site for purposes of sharing and
        displaying of any portion of the Content to which you have properly
        gained access solely for your personal, non-commercial use, unless
        stated otherwise. We reserve all rights not expressly granted to you in
        and to the Site, the Content and the Marks.
      </h3>
      <h2 className="font-Oswald md:text-4xl text-3xl font-bold my-4">
        Modifications and Interruptions
      </h2>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        27. We reserve the right to change, modify, or remove the contents of
        the Site at any time or for any reason at our sole discretion without
        notice. However, we have no obligation to update any information on our
        Site. We also reserve the right to modify or discontinue all or part of
        the Site without notice at any time.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        28. We will not be liable to you or any third party for any
        modification, price change, suspension, or discontinuance of the Site.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        29. We cannot guarantee the Site will be available at all times. We may
        experience hardware, software, or other problems or need to perform
        maintenance related to the Site, resulting in interruptions, delays, or
        errors.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        30. We reserve the right to change, revise, update, suspend,
        discontinue, or otherwise modify the Site at any time or for any reason
        without notice to you. You agree that we have no liability whatsoever
        for any loss, damage, or inconvenience caused by your inability to
        access or use the Site during any downtime or discontinuance of the
        Site.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        31. Nothing in these Terms of Service will be construed to oblige us to
        maintain and support the Site or to supply any corrections, updates, or
        releases in connection therewith.
      </h3>
      <h2 className="font-Oswald md:text-4xl text-3xl font-bold my-4">
        Dispute Resolution
      </h2>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        32. In the event of a dispute arising under the contract concluded on
        Terms of Service set forth herein, brought by either you or us
        (collectively, the “Parties”), the Parties will endeavor to resolve the
        matter amicably first. Any dispute arising under the contract and other
        legal action of whatever nature, shall be governed by laws.
      </h3>
      <h2 className="font-Oswald md:text-4xl text-3xl font-bold my-4">
        Corrections{" "}
      </h2>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        33. There may be information on the Site that contains typographical
        errors, inaccuracies, or omissions that may relate to the Site,
        including descriptions, pricing, availability, and various other
        information. We reserve the right to correct any errors, inaccuracies,
        or omissions and to change or update the information on the Site at any
        time, without prior notice.
      </h3>
      <h2 className="font-Oswald md:text-4xl text-3xl font-bold my-4">
        General Disclaimer
      </h2>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        34. The site is provided on an as-is and as-available basis. You agree
        that your use of the site and our services will be at your sole risk. To
        the fullest extent permitted by law, we disclaim all warranties, express
        or implied, in connections with the Site and your use thereof,
        including, and without limitation, the implied warranties of
        merchantability, fitness for a particular purpose and noninfringement.
        We make no warranties or representations about the accuracy or
        completeness of the Site’s content or the content of any websites linked
        to the site and we will assume no liability or responsibility for any:
      </h3>
      <ul className=" md:text-lg md:leading-none mb-2 list-disc list-inside">
        <li>errors, mistakes, or inaccuracies of content and materials</li>
        <li>
          personal injury or property damage, of any nature whatsoever,
          resulting from your access to and use of the site
        </li>
        <li>
          unauthorized access to or use of our secure servers or all personal
          data or financial information stored therein
        </li>
        <li>interruption or cessation of transmission to or from the site</li>
        <li>
          any bugs, viruses, Trojan horses, or the like which may be transmitted
          to or through the site by any third party, and/or
        </li>
        <li>
          any errors or omissions in any content and materials or for any loss
          or damage of any kind incurred as a result of the use of any content
          posted, transmitted or otherwise made available via the site. We do
          not warrant, guarantee, or assume responsibility for any product or
          service advertised, or offered by a third party through the site, any
          hyperlinked website, or any website or mobile application featured in
          any banner or other advertising, and we will not be a party to or in
          any way be responsible for monitoring any transaction between you any
          third-party providers of products or services.
        </li>
      </ul>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        35. As with making transactions through any medium or in any
        environment, you should use your best judgment and exercise caution
        where appropriate.
      </h3>
      <h2 className="font-Oswald md:text-4xl text-3xl font-bold my-4">
        Limitations of Liability
      </h2>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        36. To the fullest extent permitted by law, in no event will we our
        directors, employees, or agents be liable to you or any third party for
        any direct, indirect, consequential, exemplary, incidental, special, or
        punitive damages, including lost profit, lost revenue, loss of data, or
        other damages arising from your use of the Site and our Services. This
        limitation does not apply to your consumer rights.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        37. Visiting the Site, sending us e-mails, and completing online forms
        constitute electronic communications, you consent to receive electronic
        communications. You hereby waive any rights or requirements under any
        statutes, regulations, rules, ordinances, or other laws in any
        jurisdiction which require an original signature or delivery or
        retention of non-electronic records, or to payments or the granting of
        credits by any means other than electronic means.
      </h3>
      <h2 className="font-Oswald md:text-4xl text-3xl font-bold my-4">
        Final Provisions
      </h2>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        38. These Terms of Service and any policies or operating rules posted by
        us on the Site constitute the entire agreement and understanding between
        you and us. Our failure to exercise or enforce any right or provision of
        these Terms of Service shall not operate as a waiver of such right or
        provision.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        39. These Terms of Service operate to the fullest extent permissible by
        law. We may assign any or all our rights and obligations to others at
        any time. We shall not be responsible or liable for any loss, damage,
        delay, or failure to act caused by any cause beyond our reasonable
        control.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        40. If any provision or part of a provision of these Terms of Service is
        determined to be unlawful, void, or unenforceable, that provision or
        part of the provision is deemed severable from these Terms of Service
        and does not affect the validity and enforceability of any remaining
        provisions.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        41. There is no joint venture, partnership, employment or agency
        relationship created between you and us as a result of these Terms of
        Service or use of the Site. You agree that these Terms of Service will
        not be construed against us by virtue of having drafted them.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        42. You hereby waive any and all defenses you may have based on the
        electronic form of these Terms of Service and the lack of signing by the
        parties hereto to execute these Terms of Service.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        43. We reserve the right, in our sole discretion, to make changes or
        modifications to these Terms of Service at any time and for any reason.
        We will alert you about any changes to these Terms of Service, using the
        e-mail address you provided. If you do not agree with the updates to
        these Terms of Service, let us know within 7 days of receiving an alert.
        Lack of timely objection means you agree to the new version Terms of
        Service.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        44. These Terms of Service remain binding until you use or have a valid
        account on our Site and until you pay us all the remaining fees,
        commissions and remuneration, 2 years after that date, and later - to
        extent implied by the nature of rights and obligations created under
        these Terms of Service, in particular until the end of limitation
        periods for any legal claims.
      </h3>
      <h3 className="font-Oswald md:text-2xl text-xl font-medium my-4">
        45. The Parties may agree an earlier termination of the Terms of Service
      </h3>
    </section>
  )
}

export default Terms
